### PR TITLE
Improve daemon_handler

### PR DESCRIPTION
**Pull request by flying-sheep**
Just some code improvements

### CODE REVIEW

**Comment by flying-sheep** [comment]
done

**Comment by flying-sheep** [comment]
are you still interested in this?

**Comment by l0drex** [comment]
Yes sorry, I'm currently in exam phase and don't have much time. The build is still failing unfortunatly

**Comment by flying-sheep** [comment]
Since I didn’t change anything about the native dependencies, it’s simply an intermittent failure.

As maintainer of this repo, you can re-trigger builds using the GH actions UI.

I did the same by adding a useless empty commit.

**Comment by flying-sheep** [comment]
oops, that’s what happens when I edit with the GitHub UI instead of something good.

**Pull request merged**
